//! GBK <-> UTF-8 for CTP char fields.
//!
//! Every CTP string on the wire is GBK (知识库 §8: "CTP 字符串一律 GBK").
//! The core works in Rust `String`s, so the struct mirrors' `cstr` / `set_cstr`
//! convert at the field boundary. The double-byte table is generated by
//! `tools/gen_gbk_table.py`; ASCII passes through unchanged.

use std::collections::HashMap;
use std::sync::OnceLock;

use crate::generated::gbk_table::{DECODE, TRAILS};

fn slot(lead: u8, trail: u8) -> Option<usize> {
    if !(0x81..=0xFE).contains(&lead) || !(0x40..=0xFE).contains(&trail) || trail == 0x7F {
        return None;
    }
    Some((lead - 0x81) as usize * TRAILS + (trail - 0x40) as usize)
}

/// Decode GBK bytes; an invalid or unmapped byte becomes U+FFFD.
pub fn decode(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        let b = bytes[i];
        if b < 0x80 {
            out.push(b as char);
            i += 1;
            continue;
        }
        if let Some(code) = bytes
            .get(i + 1)
            .and_then(|&t| slot(b, t))
            .map(|s| DECODE[s])
            .filter(|&c| c != 0)
        {
            out.push(char::from_u32(code as u32).unwrap_or('\u{FFFD}'));
            i += 2;
        } else {
            out.push('\u{FFFD}');
            i += 1;
        }
    }
    out
}

fn encoder() -> &'static HashMap<u16, [u8; 2]> {
    static TABLE: OnceLock<HashMap<u16, [u8; 2]>> = OnceLock::new();
    TABLE.get_or_init(|| {
        let mut map = HashMap::with_capacity(22_000);
        for (i, &code) in DECODE.iter().enumerate() {
            if code != 0 {
                let lead = 0x81 + (i / TRAILS) as u8;
                let trail = 0x40 + (i % TRAILS) as u8;
                map.entry(code).or_insert([lead, trail]);
            }
        }
        map
    })
}

/// Encode to GBK, returning the bytes plus the end offset of every encoded
/// character (so a fixed-width field can truncate on a character boundary).
/// A character with no GBK mapping becomes `?`.
fn encode_with_bounds(s: &str) -> (Vec<u8>, Vec<usize>) {
    let mut out = Vec::with_capacity(s.len());
    let mut ends = Vec::with_capacity(s.len());
    for ch in s.chars() {
        let c = ch as u32;
        if c < 0x80 {
            out.push(c as u8);
        } else if let Some(pair) = u16::try_from(c).ok().and_then(|c| encoder().get(&c)) {
            out.extend_from_slice(pair);
        } else {
            out.push(b'?');
        }
        ends.push(out.len());
    }
    (out, ends)
}

/// Encode a string to GBK bytes (unmapped characters become `?`).
pub fn encode(s: &str) -> Vec<u8> {
    encode_with_bounds(s).0
}

/// Write `s` as GBK into a fixed CTP char field, NUL-padded. Truncation never
/// splits a double-byte character.
pub fn write_field(buf: &mut [u8], s: &str) {
    let (bytes, ends) = encode_with_bounds(s);
    let n = ends
        .iter()
        .copied()
        .take_while(|&e| e <= buf.len())
        .last()
        .unwrap_or(0);
    buf[..n].copy_from_slice(&bytes[..n]);
    for b in buf.iter_mut().skip(n) {
        *b = 0;
    }
}

/// Read a NUL-terminated GBK CTP char field.
pub fn read_field(buf: &[u8]) -> String {
    let end = buf.iter().position(|&b| b == 0).unwrap_or(buf.len());
    decode(&buf[..end])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_gbk_bytes() {
        // "资金不足" in GBK
        let gbk = [0xD7, 0xCA, 0xBD, 0xF0, 0xB2, 0xBB, 0xD7, 0xE3];
        assert_eq!(encode("资金不足"), gbk);
        assert_eq!(decode(&gbk), "资金不足");
        assert_eq!(encode("CTP:资金不足")[..4], *b"CTP:");
    }

    #[test]
    fn field_roundtrip_and_boundary_truncation() {
        let mut buf = [0xFFu8; 6];
        write_field(&mut buf, "螺纹钢");
        // 3 chars x 2 bytes fill the field exactly
        assert_eq!(read_field(&buf), "螺纹钢");
        let mut small = [0xFFu8; 5];
        write_field(&mut small, "螺纹钢");
        // the third character does not fit and is dropped whole
        assert_eq!(small[4], 0);
        assert_eq!(read_field(&small), "螺纹");
        let mut ascii = [0u8; 4];
        write_field(&mut ascii, "rb2601");
        assert_eq!(&ascii, b"rb26");
    }

    #[test]
    fn unmapped_and_invalid() {
        assert_eq!(encode("😀"), b"?");
        assert_eq!(decode(&[0x81]), "\u{FFFD}");
        assert_eq!(decode(&[0xFF, b'a']), "\u{FFFD}a");
    }
}
