#!/usr/bin/env python3
"""Generate the GBK double-byte decode table for the Rust wire crate.

CTP strings (ErrorMsg, InstrumentName, StatusMsg ...) are GBK on the wire.
The core builds with zero external crates, so the table is generated once
from Python's stdlib `gbk` codec and checked in, the same policy as the
struct mirrors in `generated/structs.rs`.

Layout: one u16 per (lead, trail) slot, lead 0x81..=0xFE, trail 0x40..=0xFE
(0x7F is never a valid trail and stays 0). 0 = unmapped.

Usage:
    python tools/gen_gbk_table.py
"""
import os

LEADS = range(0x81, 0xFF)
TRAILS = range(0x40, 0xFF)

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "core", "ctpbuddy-wire", "src", "generated", "gbk_table.rs")


def main() -> None:
    values = []
    for lead in LEADS:
        for trail in TRAILS:
            code = 0
            if trail != 0x7F:
                try:
                    ch = bytes((lead, trail)).decode("gbk")
                except UnicodeDecodeError:
                    ch = ""
                if len(ch) == 1 and ord(ch) <= 0xFFFF:
                    code = ord(ch)
            values.append(code)
    lines = [
        "// @generated by tools/gen_gbk_table.py from Python's stdlib gbk codec. DO NOT EDIT.",
        "// Index: (lead - 0x81) * %d + (trail - 0x40); 0 = unmapped." % len(TRAILS),
        "",
        "pub(crate) const TRAILS: usize = %d;" % len(TRAILS),
        "",
        "pub(crate) static DECODE: [u16; %d] = [" % len(values),
    ]
    for i in range(0, len(values), 16):
        lines.append("    " + ", ".join("0x%04X" % v for v in values[i:i + 16]) + ",")
    lines.append("];")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s (%d slots, %d mapped)" % (os.path.abspath(OUT), len(values), sum(1 for v in values if v)))


if __name__ == "__main__":
    main()
